POST http://localhost:8080/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3MDQ5NjkxOTQsInVzZXJJZCI6MX0.dwNu8frp87JbPCXoUOcWD0qzadDYZk-nhPfXbuyqVk0

{
    "title":"Title of todo",
    "description":"Description of todo",
    "dateTime":"2024-01-01T09:30:00.000Z"
}