package db_const

const CREATE_USERS_TABLE = `
CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL
)
`
const CREATE_TODOS_TABLE = `
CREATE TABLE IF NOT EXISTS todos (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	description TEXT NOT NULL,
	dateTime DATETIME NOT NULL,
	user_id INTEGER,
	FOREIGN KEY(user_id) REFERENCES users(id)
)
`
const CREATE_TODO_USERS_TABLE = `
	CREATE TABLE IF NOT EXISTS todoUsers (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER,
		todo_id INTEGER,
		FOREIGN KEY(user_id) REFERENCES users(id),
		FOREIGN KEY(todo_id) REFERENCES todos(id)
	)
	`
